server:
  port: 8090
  
spring:
  application:
    name: APIGateWay
  cloud:
    gateway:
      routes:
        - id: ReviewService
          uri: lb://ReviewService
          predicates:
            - Path=/reviews/**
        - id: BorrowingService
          uri: lb://BorrowingService
          predicates:
            - Path=/borrowings/**
        - id: CustomerService
          uri: lb://CustomerService
          predicates:
            - Path=/customers/**
        - id: BookCommandService
          uri: lb://BookCommandService
          predicates:
            - Path=/bookservice/**
        - id: BookQueryService
          uri: lb://BookQueryService
          predicates:
            - Path=/books/**

  zipkin:
    base-url: http://localhost:9411/

  sleuth:
    sampler:
      probability: 1 #100% (default = 10%)

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8761/eureka/


